### ISSUE TITLE
Is it possible to use libhantek6xx4 with OpenHantek project?

### ISSUE THREAD

**Issue by demonlibra** [pvachon/libhantek6xx4#1]
Good day.
Is it possible to use your library libhantek6xx4 with OpenHantek project?

Thanks you.

**Comment by pvachon** [comment]
Hi there -- unfortunately, the library is still incomplete. Many of the pieces needed are there, but not quite put together. The library is very much a work in progress, and needs some extra hands to finish the work on it.
